// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: link_shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLinkReq) Reset() {
	*x = GetLinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkReq) ProtoMessage() {}

func (x *GetLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_link_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkReq.ProtoReflect.Descriptor instead.
func (*GetLinkReq) Descriptor() ([]byte, []int) {
	return file_link_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *GetLinkReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLinkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLinkRes) Reset() {
	*x = GetLinkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRes) ProtoMessage() {}

func (x *GetLinkRes) ProtoReflect() protoreflect.Message {
	mi := &file_link_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRes.ProtoReflect.Descriptor instead.
func (*GetLinkRes) Descriptor() ([]byte, []int) {
	return file_link_shortener_proto_rawDescGZIP(), []int{1}
}

type GetPingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPingRes) Reset() {
	*x = GetPingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_link_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPingRes) ProtoMessage() {}

func (x *GetPingRes) ProtoReflect() protoreflect.Message {
	mi := &file_link_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPingRes.ProtoReflect.Descriptor instead.
func (*GetPingRes) Descriptor() ([]byte, []int) {
	return file_link_shortener_proto_rawDescGZIP(), []int{2}
}

var File_link_shortener_proto protoreflect.FileDescriptor

var file_link_shortener_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x32, 0x71, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x69, 0x73, 0x68, 0x61, 0x67, 0x61, 0x76, 0x72, 0x69, 0x6e,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_link_shortener_proto_rawDescOnce sync.Once
	file_link_shortener_proto_rawDescData = file_link_shortener_proto_rawDesc
)

func file_link_shortener_proto_rawDescGZIP() []byte {
	file_link_shortener_proto_rawDescOnce.Do(func() {
		file_link_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_shortener_proto_rawDescData)
	})
	return file_link_shortener_proto_rawDescData
}

var file_link_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_link_shortener_proto_goTypes = []interface{}{
	(*GetLinkReq)(nil),    // 0: api.GetLinkReq
	(*GetLinkRes)(nil),    // 1: api.GetLinkRes
	(*GetPingRes)(nil),    // 2: api.GetPingRes
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_link_shortener_proto_depIdxs = []int32{
	0, // 0: api.apiService.GetLink:input_type -> api.GetLinkReq
	3, // 1: api.apiService.GetPing:input_type -> google.protobuf.Empty
	1, // 2: api.apiService.GetLink:output_type -> api.GetLinkRes
	2, // 3: api.apiService.GetPing:output_type -> api.GetPingRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_link_shortener_proto_init() }
func file_link_shortener_proto_init() {
	if File_link_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_link_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_link_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_shortener_proto_goTypes,
		DependencyIndexes: file_link_shortener_proto_depIdxs,
		MessageInfos:      file_link_shortener_proto_msgTypes,
	}.Build()
	File_link_shortener_proto = out.File
	file_link_shortener_proto_rawDesc = nil
	file_link_shortener_proto_goTypes = nil
	file_link_shortener_proto_depIdxs = nil
}
